# Generated by Django 3.0 on 2020-08-23 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('mail', models.CharField(max_length=200, verbose_name='Почта')),
                ('comment', models.CharField(max_length=200, verbose_name='Коммент')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Заявка cо страницы контактов',
                'verbose_name_plural': 'Заявка со страницы контактов',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('slug_category', models.SlugField(unique=True, verbose_name='URL (добавляется автоматически)')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('img1', models.ImageField(upload_to='static/img/products/', verbose_name='Изображение 1')),
                ('img2', models.ImageField(upload_to='static/img/products/', verbose_name='Изображение 2')),
                ('slug_product', models.SlugField(unique=True, verbose_name='URL (добавляется автоматически)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена')),
                ('price_disc', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Цена со скидкой')),
                ('discount', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True, verbose_name='Размер скидки')),
                ('new', models.BooleanField(verbose_name='Новый товар')),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, verbose_name='Рейтинг')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainasia.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
