# Generated by Django 3.0 on 2020-08-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainasia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='describe',
            field=models.CharField(default=1, max_length=250, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
