# Generated by Django 3.0 on 2020-09-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainasia', '0004_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='describe',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
