# Generated by Django 3.0 on 2020-09-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainasia', '0008_auto_20200918_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img2',
            field=models.ImageField(default=1, upload_to='static/img/products/', verbose_name='Изображение 2'),
            preserve_default=False,
        ),
    ]
