# Generated by Django 3.0 on 2020-08-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Сам текст')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображения блога')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображения блога')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображения блога')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображения блога')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображения блога')),
                ('photo5', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображения блога')),
                ('photo6', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображения блога')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блог',
            },
        ),
    ]
