# Generated by Django 3.1 on 2020-08-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200820_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='new',
            field=models.BooleanField(verbose_name='Новый товар'),
        ),
    ]
