# Generated by Django 3.1 on 2020-08-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_product_price_disc'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2, verbose_name='Размер скидки'),
            preserve_default=False,
        ),
    ]
