# Generated by Django 3.1 on 2020-08-19 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_product_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_disc',
        ),
    ]
