# Generated by Django 3.1 on 2020-08-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_product_price_disc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True, verbose_name='Размер скидки'),
        ),
    ]
