# Generated by Django 3.1 on 2020-08-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img1',
            field=models.ImageField(default=1, upload_to='static/img/products/', verbose_name='Изображение 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='img2',
            field=models.ImageField(default=1, upload_to='static/img/products/', verbose_name='Изображение 2'),
            preserve_default=False,
        ),
    ]
